### ISSUE TITLE
www.impallari.com libre-baskerville link dead

### ISSUE THREAD

**Issue by wilx** [impallari/Libre-Baskerville#2]
The <http://www.impallari.com/projects/overview/libre-baskerville> link seems to be dead.

**Comment by impallari** [comment]
New Link is https://impallari.com/revivals/baskerville/

**Comment by 7ombie** [comment]
It's dead again.

**Comment by archfrog** [comment]
Still dead.  The site has been suspended, somebody needs to pay a bill or reactivate it.
